version: 2

jobs:

  8.8-macos:
    macos:
      xcode: "11.4.0"
    environment:
      BRANCH: asterius-8.8
      JOBS: 4
      XZ_OPT: -9eT4
    steps:
      - run:
          name: Install dependencies
          command: |
            brew update
            brew upgrade
            brew install \
              coreutils \
              gnu-tar \
              sphinx-doc
            mkdir -p ~/.local/bin
            curl -L https://github.com/commercialhaskell/stack/releases/download/v2.3.0.1/stack-2.3.0.1-osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
            ~/.local/bin/stack --resolver nightly-2020-04-18 --no-terminal install \
              alex \
              happy \
              hscolour
      - run:
          name: Initialize ghc repo
          command: |
            cd /tmp
            git clone --recurse-submodules --branch $BRANCH --depth=1 https://github.com/TerrorJack/ghc.git
      - checkout
      - run:
          name: Compile GHC
          no_output_timeout: 1h
          command: |
            export PATH=~/.local/bin:$(~/.local/bin/stack path --compiler-bin):/usr/local/opt/sphinx-doc/bin:$PATH
            mv .circleci/build-macos.mk /tmp/ghc/mk/build.mk
            cd /tmp/ghc
            ./boot
            ./configure
            make -j$JOBS
            make binary-dist
            mkdir /tmp/ghc-bindist
            mv *.tar.* /tmp/ghc-bindist/
            (ls -l /tmp/ghc-bindist && sha256sum -b /tmp/ghc-bindist/*) > /tmp/ghc-bindist/sha256.txt
      - store_artifacts:
          path: /tmp/ghc-bindist

workflows:
  version: 2
  build:
    jobs:
      - 8.8-macos
